### ISSUE TITLE
Simple csharp with SHA256CryptoServiceProvider

### ISSUE THREAD

**Issue by pengzeshan** [kekyo/IL2C#92]
I have a simple csharp code related to SHA256CryptoServiceProvider. Here is a simple example csharp code:
using System;
using System.Security.Cryptography;
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var ha = new SHA256CryptoServiceProvider();
            Console.WriteLine("hello again");
        }
    }
}

Error message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "Translate" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at IL2C.Metadata.MethodInformation.get_IsConstructor() in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\Metadata\MethodInformation.cs:line 164
   at IL2C.ILConverters.NewobjConverter.Prepare(IMethodInformation ctor, DecodeContext decodeContext) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\ILConveters\NewConverters.cs:line 77
   at IL2C.ILConverters.ILConverter`1.Prepare(Object operand, DecodeContext decodeContext) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\ILConveters\ILConverter.cs:line 61
   at IL2C.AssemblyPreparer.<>c__DisplayClass3_2.<PrepareMethodBody>b__11(ILBody ilBody) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\AssemblyPreparer.cs:line 138
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at IL2C.AssemblyPreparer.PrepareMethodBody(IPrepareContext prepareContext, IMethodInformation method) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\AssemblyPreparer.cs:line 134
   at IL2C.AssemblyPreparer.PrepareMethod(IPrepareContext prepareContext, IMethodInformation method) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\AssemblyPreparer.cs:line 256
   at IL2C.AssemblyPreparer.<>c__DisplayClass5_0.<Prepare>b__4(<>f__AnonymousType1`2 <>h__TransparentIdentifier0) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\AssemblyPreparer.cs:line 310
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at IL2C.AssemblyPreparer.Prepare(TranslateContext translateContext, Func`2 predictType, Func`2 predictMethod) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\AssemblyPreparer.cs:line 305
   at IL2C.AssemblyPreparer.Prepare(TranslateContext translateContext) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\AssemblyPreparer.cs:line 320
   at IL2C.SimpleDriver.Translate(TextWriter logw, CodeTextStorage storage, Boolean readSymbols, Boolean enableBundler, TargetPlatforms targetPlatform, DebugInformationOptions debugInformationOptions, String assemblyPath) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\SimpleDriver.cs:line 39
   at IL2C.SimpleDriver.TranslateAll(TextWriter logw, String outputPath, Boolean readSymbols, Boolean enableCpp, Boolean enableBundler, TargetPlatforms targetPlatform, DebugInformationOptions debugInformationOptions, IEnumerable`1 assemblyPaths) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\SimpleDriver.cs:line 121
   at IL2C.SimpleDriver.TranslateAll(TextWriter logw, String outputPath, Boolean readSymbols, Boolean enableCpp, Boolean enableBundler, TargetPlatforms targetPlatform, DebugInformationOptions debugInformationOptions, String[] assemblyPaths) in C:\cygwin\home\damon.peng\workspace\workForCH\dotNet\IL2C\IL2C.Core\SimpleDriver.cs:line 142
   at IL2C.Translate.Execute() in D:\PROJECT\IL2C\IL2C.Tasks\Translate.cs:line 86
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ConsoleApp1	C:\Users\damon.peng\.nuget\packages\il2c.build\0.4.113\build\IL2C.Build.targets	19	

Here is the IL2C.Build version used to trigger the above error:
 <PackageReference Include="IL2C.Build" Version="0.4.113" />

**Comment by kekyo** [comment]
@pengzeshan Sorry delay, unfortunately SHA256CryptoServiceProvider implementation doesn't port into IL2C. I think if I port it:

* Pure sha256 native code (by C lang) links into your app (with ld option).
* Write bridge code fragment by IL2C/Invoke semanrics or P/Invoke's.
  * Caution: P/Invoke support is very experimental stage and lack a lot of features, so I recommend using IL2C/Invoke.

**Comment by kekyo** [comment]
If you want to get more IL2C/Invoke information, I recommend  referring my blog entry [Try writing code using both the Azure Sphere Development Kit and C#](https://www.kekyo.net/2019/01/04/6917)

* IL2C already dropped `Azure Sphere environment` ([Reason](https://github.com/kekyo/IL2C/issues/73#issuecomment-492470484)), but I think fill and understand this feature.
* It's bit older, very poor English :)

**Comment by kekyo** [comment]
Related #91 , close this issue.
